### PR TITLE
Add `duration` filter

### PR DESCRIPTION
**Pull request by chris-barrett-ddts**
This is a filter to get the date a certain number of days from todays date.

This is useful if you're displaying an SLA on a confirmation page, by giving the user an actual date rather than leaving them to work out when 5 days from now is.

It uses the Luxon Duration object.

### CODE REVIEW

**Review by fofr — COMMENTED** [review]
Nice!

Can I suggest the filter name:

```
dateDaysFromNow
```

**Comment by paulrobertlloyd** [comment]
Nice! Was thinking about this, wonder if you could provide an option for the unit type, something along the lines of:

```njk
Date is 2023-05-11T09:00:59

{{ 5 | dateFromNow }}
2023-05-16T09:00:59

{{ 5 | dateFromNow({unit: "days"}) }} // default
2023-05-16T09:00:59

{{ 5 | dateFromNow({unit: "weeks"}) }}
2023-06-15T09:00:59

{{ 5 | dateFromNow({unit: "months"}) }}
2023-11-11T09:00:59

{{ 5 | dateFromNow({unit: "years"}) }}
2028-11-05T09:00:59
```

Would that be useful?

**Comment by chris-barrett-ddts** [comment]
> Nice! Was thinking about this, wonder if you could provide an option for the unit type, something along the lines of:
> 
> ```
> Date is 2023-05-11T09:00:59
> 
> {{ 5 | dateFromNow }}
> 2023-05-16T09:00:59
> 
> {{ 5 | dateFromNow({unit: "days"}) }} // default
> 2023-05-16T09:00:59
> 
> {{ 5 | dateFromNow({unit: "weeks"}) }}
> 2023-06-15T09:00:59
> 
> {{ 5 | dateFromNow({unit: "months"}) }}
> 2023-11-11T09:00:59
> 
> {{ 5 | dateFromNow({unit: "years"}) }}
> 2028-11-05T09:00:59
> ```
> 
> Would that be useful?

Yeah that's a good point. Just as i was finishing this PR I was wondering whether the scope should be expanded out a bit more. 

Certainly putting units in could work. But I was also wondering whether it should work a bit more like the "govukDate" filter. 

Where the user could enter a date as well as now/today, then the value and unit type would be passed in as parameters.

```
{{ "now" | duration(5, "days") }}
2023-05-16T09:00:59

{{ "2023-05-15" | duration(5, "days") }}
2023-05-20T09:00:59

{{ "2023-05-11" | duration(5, "weeks") }}
2023-06-11T09:00:59

{{ "2023-05-11" | duration(5, "months") }}
2023-10-11T09:00:59

{{ "2023-05-11" | duration(5, "years") }}
2028-05-11T09:00:59
```


Let me know what you think?

**Comment by paulrobertlloyd** [comment]
Yeah, I like that. This also means you could do the following:

```json
"data": {
  "submitted": "2023-05-11"
}
```

```njk
We will respond to your submission by {{ data.submitted | isoDateFromDateInput | duration(12, "weeks") | govukDate }}.
```

```
We will respond to your submission by 13 August 2023.
```

**Comment by chris-barrett-ddts** [comment]
- Renamed to duration
- Users can pass in a date string or use the "now/today" keywords
- Users can specify the units, days, weeks, months and years (default is day)

**Comment by paulrobertlloyd** [comment]
Love it! Thanks @chris-barrett-ddts 😃

**Pull request merged**
